import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { storyTimeData } from '../../data/storyTimeData';
import './StoryTime.css';

const StoryTimePlayer = () => {
    const { storyId } = useParams();
    const navigate = useNavigate();
    const story = storyTimeData.find(s => s.id === storyId);
    const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
    const [showMoral, setShowMoral] = useState(false);

    useEffect(() => {
        if (!story) return;

        // Play MP3 audio generated by python script
        let audioObj = null;
        if (!showMoral && story.slides[currentSlideIndex]) {
            audioObj = new Audio(`http://localhost:5001/audio/storyTime/${story.id}_slide_${story.slides[currentSlideIndex].slideIndex}.mp3`);
            audioObj.play().catch(e => console.log("Audio play blocked by browser. Click next to start.", e));
        } else if (showMoral) {
            audioObj = new Audio(`http://localhost:5001/audio/storyTime/${story.id}_moral.mp3`);
            audioObj.play().catch(e => console.log("Audio play blocked by browser", e));
        }

        // Auto advance every 7 seconds
        const timer = setTimeout(() => {
            handleNext();
        }, 7000);

        return () => {
            clearTimeout(timer);
            if (audioObj) {
                audioObj.pause();
                audioObj.currentTime = 0;
            }
        }
    }, [currentSlideIndex, story, showMoral]);

    if (!story) {
        return <div>Story not found</div>;
    }

    const handleNext = () => {
        if (showMoral) {
            navigate(`/story-time/quiz/${story.id}`);
            return;
        }
        if (currentSlideIndex < story.slides.length - 1) {
            setCurrentSlideIndex(prev => prev + 1);
        } else {
            setShowMoral(true);
        }
    };

    const handlePrev = () => {
        if (showMoral) {
            setShowMoral(false);
            return;
        }
        if (currentSlideIndex > 0) {
            setCurrentSlideIndex(prev => prev - 1);
        }
    };

    const slide = story.slides[currentSlideIndex];

    return (
        <div className="story-player-container">
            <div className="player-topbar">
                <button className="back-btn" onClick={() => navigate('/story-time')}>← Back to Stories</button>
                <div className="progress-bar">
                    <div className="progress-fill" style={{ width: `${((currentSlideIndex + (showMoral ? 2 : 1)) / (story.slides.length + 1)) * 100}%` }}></div>
                </div>
            </div>

            <div className="player-content">
                <AnimatePresence mode="wait">
                    {showMoral ? (
                        <motion.div
                            key="moral"
                            initial={{ opacity: 0, scale: 0.8 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0, scale: 1.2 }}
                            className="moral-slide"
                        >
                            <h1>Moral of the Story</h1>
                            <h2>{story.moral}</h2>
                            <button className="start-quiz-btn" onClick={() => navigate(`/story-time/quiz/${story.id}`)}>
                                Start Quiz! 🎯
                            </button>
                        </motion.div>
                    ) : (
                        <motion.div
                            key={currentSlideIndex}
                            initial={{ opacity: 0, x: 100 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -100 }}
                            className="slide-content"
                        >
                            <div
                                className="slide-image"
                                style={{ backgroundImage: `url(http://localhost:5001/images/storyTime/${slide.image})` }}
                            />
                            <p className="slide-text">{slide.sentence}</p>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            <div className="player-controls">
                <button onClick={handlePrev} disabled={currentSlideIndex === 0 && !showMoral}>Previous</button>
                <button onClick={handleNext}>{showMoral ? "Go to Quiz" : "Next"}</button>
            </div>
        </div>
    );
};

export default StoryTimePlayer;
